# Generated by Django 2.2.2 on 2019-06-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190607_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='showtimes',
        ),
        migrations.AddField(
            model_name='showtimes',
            name='cinema',
            field=models.ForeignKey(null=True, on_delete=None, to='myapp.Cinema'),
        ),
        migrations.AddField(
            model_name='showtimes',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=None, to='myapp.Movie'),
        ),
    ]
