# Generated by Django 2.2.2 on 2019-06-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190607_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtimes',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
