# Generated by Django 2.2.2 on 2019-06-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_showtimes_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtimes',
            name='remaining_cap',
            field=models.IntegerField(default=0),
        ),
    ]
